---
title: 'Event Report: Interview Prep for the Job'
author: James Del Mutolo
date: '2025-06-21'
slug: event-report-interview-prep-for-the-job
categories: []
tags: []
---

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;On June 17th, 2025, I attended a virtual workshop through the USF Center for Career and Professional Development titled Interview Prep for the Job. This workshop was hosted on Microsoft Teams and was presented by USF career coach Alexandra Kulawsky. The goal of the workshop is to provide students with information about interview techniques, tips, and strategies that can be used to navigate the interview process and stand out among other candidates. While the content of the presentation does not directly apply to the field of information studies and technology, the topics and resources discussed are relevant to anyone trying to improve their interview skills, no matter what their career goals may be. As a student aiming to land a position in my field of study, the information presented in this workshop will provide me with more confidence throughout the job interview process. The following paragraphs will discuss the key points of the workshop and how I can apply them to develop my interview skills.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Alexandra began the presentation by going over different types of interview questions starting with behavioral-based questions. These types of questions assess the candidate's behavior or decisions given a certain situation. Personality-based questions are designed to test a candidate's ability to reflect on and articulate themselves. The STAR-LA method is useful for answering situational questions. It provides a step-by-step process starting with STAR, which is an acronym for, situation, task, action, and results. One would first describe a relevant situation, the task at hand, the actions taken, and the final result. This is generally sufficient, but an answer can be taken a step further with the two optional steps, LA, which stands for learning moment and application. Alexandra also touched on skill-based interview questions which can be applicable to interviewing for information science positions. Skill-based questions are technical and may require the demonstration of skills required for the position.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;We also talked about the top competencies associated with career readiness classified by NACE (National Association of Colleges and Employers). NACE states that “[f]or new college graduates, career readiness is key to ensuring successful entrance into the workforce.” (What Is Career Readiness?, n.d.). Alexandra suggested coming up with one or two examples for each of the following competencies: Professionalism, communication, critical thinking, teamwork, technology, leadership, equity and inclusion, and career and self-development. I will work to come up with examples for each of these competencies and study them further.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Big Interview is a resource offered to USF students that allows them to practice different types of interview questions specific to different fields. Students can use this resource to view, practice, and record their answers to mock interview questions and then receive feedback on their answers from an AI algorithm. Big Interview contains banks of interview questions for various fields of work, including information science. They specifically offer resources for those applying for data analytics roles. I will make use of Big Interview to practice my interview skills for data analytics positions and other positions that apply to my field of study.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The virtual workshop, Interview Prep for the Job, provided me with great information and resources that will allow me to practice and develop my interview skills. We covered the different types of interview questions, and how to use the STAR-LA method to answer situational-based interview questions. I will continue to study the eight career readiness competencies identified by NACE to gain a better understanding of the qualities that facilitate successful career management. Finally, I will make use of Big Interview to practice mock interviews related to my field of study. Overall, this workshop provided by the Center for Career and Professional Development was very informative and I look forward to attending more in the future.

# References
What is Career Readiness? (n.d.). NACE. Retrieved June 19, 2025, from https://www.naceweb.org/career-readiness/competencies/career-readiness-defined

