---
title: 'Information Policy in the News: Cryptocurrency Corruption'
author: James Del Mutolo
date: '2025-07-06'
slug: information-policy-in-the-news-cryptocurrency-corruption
categories: []
tags: []
---
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In 2008, an individual using the pseudonym Satoshi Nakamoto outlined the idea that money could be decentralized, allowing individuals to transfer funds directly to one another without relying on banks, governments, or other centralized financial institutions (Nakamoto, 2008). The framework defined by Nakamoto was used to create Bitcoin and has since been used to develop a wide range of cryptocurrencies and decentralized financial systems. More recently, cryptocurrencies have gained the attention of investors who find that “not only has a new kind of currency and transaction network arisen, but also a new kind of investment product” (Trimborn et al., 2019, p. 280). Cryptocurrencies as an investment product have introduced both new opportunities and significant challenges for investors and regulators alike. As cryptocurrencies have only developed very recently, regulation has struggled to keep pace with the rapid innovation and global adoption of these digital assets. While these regulatory gaps have allowed for unbounded innovation, it has also opened a door for market manipulation activities such as insider trading, front running, pump-and-dumps, and many other schemes that manipulate investors (Department of Financial Protection and Innovation, n.d.). The following sections will discuss recent events that highlight the issue of corruption in the cryptocurrency industry, identify the core problem of inadequate oversight and regulation, review legislative efforts to thwart corruption and protect investors, and assess implications for information professionals and society.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Today, anyone can create their own cryptocurrency coin using platforms such as pump.fun. Unlike the still very volatile, but slightly more stable foundational cryptocurrencies, coins created on these platforms “are often based on online jokes [and] have no inherent value. They often prove risky investments as their prices can fluctuate wildly.” (Stone, 2025). This platform allows and essentially promotes, hence its name, the manipulation of investors through pump-and-dump schemes. These activities would be illegal if performed in traditional financial markets, where regulations are enforced by agencies such as the U.S. Securities and Exchange Commission (SEC) that explicitly prohibit market manipulation (Securities Exchange Act, 1934). However, due to the lack of regulation and oversight in the decentralized cryptocurrency space, many of these schemes go unchecked. The lack of, and even dismantling of current cryptocurrency regulations (Betts, 2025), has emboldened prominent figures in their endeavors to profit massively from speculative and often deceptive coin launches, frequently at the expense of inexperienced or uninformed investors. Influencers, celebrities, even the President of the United States, Donald Trump, and First Lady, Melania Trump have promoted their own cryptocurrency projects with no disclosure about their financial interests (Jolly, 2025; Stone, 2025). The normalization of these practices not only undermines trust in the broader digital asset market, but also highlights the need for policy development that can hold individuals accountable for misleading and exploitative conduct in the cryptocurrency space.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The core problem that incentivises these schemes is the lack of regulation and penalization for engaging in them. Introduced to the Senate on May 7th, 2025, the End Crypto Corruption Act aims “[t]o amend chapter 131 (Ethics in Government) of title 5, United States Code, to prohibit the President, Vice President, Members of Congress, and individuals appointed to Senate-confirmed positions from issuing, sponsoring, or endorsing certain financial instruments, and for other purposes.” (End Crypto Corruption Act, 2025). Passing legislation such as this would be a great start to establishing accountability and public trust in both government institutions and the digital asset market. However, there is still the issue that this legislation would need to be signed into law by the very individuals it seeks to restrict, creating an inherent conflict of interest.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Information professionals serve an important role in guiding the responsible development, use, and regulation of emerging technologies like cryptocurrencies. With expertise in data management, cybersecurity, and digital literacy, they are positioned to help mitigate the risks associated with unregulated or deceptive cryptocurrency practices. They serve a key role in educating the public about the risks and ethical implications of investing in or using cryptocurrencies, especially in an environment where misinformation and hype can easily mislead uninformed individuals. By promoting digital and financial literacy, information professionals empower the public to make informed decisions regarding cryptocurrency investments.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;It is difficult to say how exactly cryptocurrency legislation will develop in the next decade, or how cryptocurrencies will be utilized for that matter. What is clear, however, is that without comprehensive regulation and stronger mechanisms of enforcement, the cryptocurrency market will continue to serve as fertile ground for unethical behavior and financial exploitation. Policymakers and information professionals must work together to create a more ethical and secure environment for the digital economy. Through thoughtful policy development and public education, it is possible to foster the innovative potential of cryptocurrencies while protecting individuals and maintaining the integrity of digital financial systems.

# References
Betts, A. (2025, April 08). Trump's justice department to disband unit investigating crypto fraud. The Guardian. https://www.theguardian.com/us-news/2025/apr/08/trump-crypto-doj

Department of Financial Protection and Innovation. (n.d.). Crypto Scam Tracker. DFPI. Retrieved July 04, 2025, from https://dfpi.ca.gov/consumers/crypto/crypto-scam-tracker/

End Crypto Corruption Act. (2025, May 07). https://www.congress.gov/bill/119th-congress/senate-bill/1668/text

Jolly, J. (2025, January 20). Melania Trump launches meme coin as crypto conflicts worry experts. The Guardian. https://www.theguardian.com/technology/2025/jan/20/donald-trump-meme-coin-price-melania-token

Nakamoto, S. (2008, August 21). Bitcoin: A Peer-to-Peer Electronic Cash System. http://dx.doi.org/10.2139/ssrn.3440802

Securities Exchange Act. (1934). [15 U.S. Code § 78i]. https://www.law.cornell.edu/wex/securities_exchange_act_of_1934

Stone, P. (2025, June 17). 'I have never seen such open corruption': Trump's crypto deals and loosening of rules shock observers. The Guardian. https://www.theguardian.com/us-news/2025/jun/17/trump-crypto-memecoin-corruption

Trimborn, S., Li, M., & Härdle, W. K. (2019, June 03). Investing with Cryptocurrencies—a Liquidity Constrained Investment Approach. Journal of Financial Econometrics, 18(2), 280-306. Oxford University Press. https://doi.org/10.1093/jjfinec/nbz016