---
title: Hypothetical Project Management Plan
author: James Del Mutolo
date: '2025-06-15'
slug: hypothetical-project-management-plan
categories: []
tags: []
---

# Project Management Plan: USF Software Licensing Database Implementation

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The University of South Florida would like to implement and manage a database that would allow the tracking of all licensed software used throughout the institution. Developing a well-thought-out plan is crucial for the timely and cost-effective implementation of the proposed project. Chapter 1 of Baars’ Project Management Handbook (2006) provides a six step process that breaks a project management plan down into smaller phases. Baars’ states that “[t]hrough this [organization] into phases, the total work load of a project is divided into smaller components, thus making it easier to monitor.”  (Baars, 2006, pg. 1-1). The following sections will outline these six steps and describe how they will be used to create a project management plan for the University of South Florida to implement their software licensing database.

# Initiation Phase

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Critical aspects of the initiation phase include, identifying the feasibility of the project, its expectations, scope, and involved parties. Baars stresses the importance that all involved parties “explicitly agree on the type of project that is being started.” (Baars, 2006, 1-2). The initiation phase of this licensing database project would start with bringing together the key stakeholders and developing a project plan. Some of the key stakeholders in this project would be the university’s IT department, the license management department (Lange, 2022), chief financial officer, and faculty who would be the end users of the database. These individuals would need to work together to establish what the desired outcome of the project will be. After establishing the feasibility of the project, its expectations, and scope, the project would need to be proposed and approved by all parties.

# Definition Phase

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In the definition phase, “the requirements that are associated with a project result are specified as clearly as possible.” (Baars, 2006, pg. 1-3). The requirements for the software licensing database are as follows.

### User-friendly Interface

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A user-friendly web based interface will be an important requirement for the project. The interface should allow users to easily access information without needing extensive database knowledge. This aspect of the project will involve the coordination of UI developers, web developers, application developers, and the senior IT administrator.

### Security

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The information within the database must be both easily accessible by authorized users, and kept secure from non-authorized users. The university’s senior IT administrator would need to oversee and delegate the process of developing a method for user access control, and ensure that all data communications are encrypted.

### Query Functionality

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Another requirement for this project is for users to be able to make queries for specific information. This functionality will need to be implemented by the database developers and application developers and will be overseen by the senior IT administrator.

# Design Phase

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The design phase of this project will involve the collaboration of all involved parties working towards creating a design for the final result of the project, following the requirements defined in the definition phase. It is important that the final design is approved and fully agreed upon, as “once the design has been chosen, it cannot be changed in a later stage of the project.” (Baars, 2006, pg. 1-5).

# Development Phase

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;“Durring the development phase, everything that will be needed to implement the project is arranged.” (Baars, 2006, pg. 1-6). This will involve identifying which aspects of the project need to be subcontracted, ordering any necessary equipment or materials, and assigning tasks and deadlines. In the development phase, it “must be clear what must be done in the implementation phase, by whom and when.” (Baars, 2006, pg. 1-6). The project would need to begin with the development of the backend of the database. Once a backend for the project has been developed, the appropriate teams can begin development on the frontend and user interface aspects of the project.

# Implementation Phase

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Once all involved parties have been assigned their duties and deadlines in the project, and all equipment and materials have been staged, the implementation phase can begin. The database developers will begin constructing the backend of the project while coordinating with the senior IT administrator and information security specialists to implement user access control and encryption. With an operational backend, the web developers and user interface developers will start working on the web based interface that the end users will ultimately be using. Once the database and web interface is deemed to be fully operational, the project will be ready to rollout.

# Follow-up Phase

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;“The central question in the follow-up phase concerns when and where the project ends.” (Baars, 2006, pg. 1-7). Baars discusses the importance of setting the boundaries of the project in the beginning to avoid confusion about when the project should be closed. The point at which the licensing database project should be closed is once the project has been fully implemented, appropriate staff have been trained on how to use it, and proper documentation has been created. Once the project has been closed, the university’s IT administration will be able to handle general maintenance and user support.

# Conclusion

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The six phases of project management defined by Baars provide a useful framework for guiding the process of developing and implementing a project. Baars mentions the importance that all parties approve of and have the same expectations as each phase develops. They also consider the possibility that in the implementation phase, “it is hardly ever possible to achieve a project result that precisely meets all of the requirements that were originally specified in the definition phase.” (Baars, 2006, pg. 1-7). While the framework provided by the six phase process is useful, it does have some limitations in that it is very rigid and linear. Later in the handbook, Baars suggests “cyclical methods of project management” that “are particularly suited for IT-development projects.” (Baars, 2006, 5-6).

# References

Baars, W. (2006). Project Management Handbook. Data Archiving and Networked Services.

Lange, M. (2022, February 01). License Management – Everything you need to know. TIMETOACT. https://www.timetoact.de/en/blog/software-asset-management/license-management-under-control